import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  eslintConfigPrettier,
  {
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
        self: "readonly",
        module: "readonly",
        require: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Buffer: "readonly",
        Uint8Array: "readonly",
        Int32Array: "readonly",
        Worker: "readonly",
        MessageEvent: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        __dirname: "readonly",
        import: "readonly",
      },
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/explicit-function-return-type": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/non-nullable-type-assertion-style": "off",
      "no-console": ["warn", { allow: ["warn", "error", "log", "table"] }],
      eqeqeq: ["error", "always"],
    },
  },
  {
    ignores: [
      "docs/.vitepress/",
      "tools/",
      "dist/",
      "build/",
      "node_modules/",
      "coverage/",
      "eslint.config.mjs",
      "jest.config.cjs",
      "venv/",
      ".venv/",
      "example/",
      "android/",
      "ios/",
      "native/",
      "data/",
      "test-data/",
      "*.js",
      "test-ptrs.ts",
      "bench_*.ts",
      "c4_benchmark2/",
      "wasm-out/",
      "scratch/",
      "scratch_*.ts",
      "scratch_test_timeout.ts",
    ],
  },
);
