#!/usr/bin/env python3
"""
gen_embedded_books.py

Converts .efbook binary opening book files into a C++ header
(native/embedded_books.hpp) so they are compiled directly into
the native addon and WASM binaries.

Also emits src/embedded-book-sizes.ts so capabilities.ts can
import EMBEDDED_BOOK_SIZES from a single auto-generated source.

Usage:
    python3 tools/gen_embedded_books.py

Outputs:
    native/embedded_books.hpp
    src/embedded-book-sizes.ts
"""

import os
import sys
import zlib

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(REPO_ROOT, "native", "embedded_books.hpp")
TS_OUTPUT = os.path.join(REPO_ROOT, "src", "embedded-book-sizes.ts")

# Books to embed: (width, height, path)
BOOKS = [
    (6, 6, "data/6x6_dense3.efbook"),
    (6, 7, "data/6x7_dense6.efbook"),
    (7, 6, "data/7x6_dense7.efbook"),
]


def to_c_array(name: str, data: bytes) -> list[str]:
    lines = []
    hex_vals = [f"0x{b:02x}" for b in data]
    # 16 bytes per line
    for i in range(0, len(hex_vals), 16):
        chunk = hex_vals[i : i + 16]
        lines.append("    " + ", ".join(chunk) + ",")
    return [
        f"static const uint8_t {name}[] = {{",
        *lines,
        "};",
        f"static const size_t {name}_SIZE = {len(data)}UL;",
    ]


def main() -> int:
    lines = [
        "// embedded_books.hpp — AUTO-GENERATED by tools/gen_embedded_books.py",
        "// DO NOT EDIT MANUALLY. Re-run the script to regenerate.",
        "//",
        "// Contains opening book data compiled directly into the binary.",
        "// Used by AdaptiveSolver to provide zero-latency book lookups.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace EmbeddedBooks {",
        "",
    ]

    total_raw = 0
    total_gz = 0

    for width, height, rel_path in BOOKS:
        path = os.path.join(REPO_ROOT, rel_path)
        if not os.path.exists(path):
            print(f"  MISSING: {rel_path} — skipping", file=sys.stderr)
            continue

        data = open(path, "rb").read()
        gz = zlib.compress(data, 9)
        total_raw += len(data)
        total_gz += len(gz)

        name = f"BOOK_{width}x{height}"
        lines.append(f"// {rel_path}: {len(data):,} bytes raw, {len(gz):,} bytes gzip")
        lines.extend(to_c_array(name, data))
        lines.append("")

    # Dispatcher: _getEmbeddedBook(w, h) → {ptr, size} or {nullptr, 0}
    lines += [
        "inline const uint8_t* getBookData(int width, int height) {",
    ]
    for width, height, rel_path in BOOKS:
        path = os.path.join(REPO_ROOT, rel_path)
        if not os.path.exists(path):
            continue
        name = f"BOOK_{width}x{height}"
        lines.append(f"    if (width == {width} && height == {height}) return {name};")
    lines += [
        "    return nullptr;",
        "}",
        "",
        "inline size_t getBookSize(int width, int height) {",
    ]
    for width, height, rel_path in BOOKS:
        path = os.path.join(REPO_ROOT, rel_path)
        if not os.path.exists(path):
            continue
        name = f"BOOK_{width}x{height}"
        lines.append(f"    if (width == {width} && height == {height}) return {name}_SIZE;")
    lines += [
        "    return 0;",
        "}",
        "",
        "} // namespace EmbeddedBooks",
    ]

    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated: {os.path.relpath(OUTPUT, REPO_ROOT)}")
    print(f"  Total raw: {total_raw:,} bytes ({total_raw // 1024} KB)")
    print(f"  Total gzip: {total_gz:,} bytes (~{total_gz // 1024} KB wire cost)")

    # Emit the TypeScript size registry
    found_books = [
        (w, h) for (w, h, rel_path) in BOOKS
        if os.path.exists(os.path.join(REPO_ROOT, rel_path))
    ]
    ts_lines = [
        "// AUTO-GENERATED by tools/gen_embedded_books.py",
        "// DO NOT EDIT MANUALLY. Re-run the script to regenerate.",
        "//",
        "// Board sizes for which an opening book is compiled directly into the binary.",
        "// Must stay in sync with native/embedded_books.hpp.",
        "",
        "export const EMBEDDED_BOOK_SIZES: ReadonlySet<string> = new Set([",
    ]
    for w, h in found_books:
        ts_lines.append(f'  "{w}x{h}",')
    ts_lines += [
        "]);",
        "",
    ]
    with open(TS_OUTPUT, "w") as f:
        f.write("\n".join(ts_lines))

    print(f"Generated: {os.path.relpath(TS_OUTPUT, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
