export enum Player {
  P1 = "P1", // Moves first
  P2 = "P2", // Moves second
}

export enum Outcome {
  Win = "Win",
  Loss = "Loss",
  Draw = "Draw",
}

export interface Connect4SolverOptions {
  width?: number;
  height?: number;
  cacheSizeMb?: number;
  heuristic?: boolean;
}

export interface AnalyzeOptions {
  threads?: number;
  maxDepth?: number;
  timeoutMs?: number;
  book?: { ptr: number };
}

export interface Evaluation {
  eval: {
    value: number; // Normalized float (+Infinity/-Infinity for exact wins, score/100 for heuristic)
  };
  outcome?: Outcome; // Only present on exact solutions
  winner?: Player | null; // null when Draw, only present on exact solutions
  movesToEnd?: number | null; // null when Draw, only present on exact solutions
  score: number; // raw score (positive = current player winning)
}

export interface PositionAnalysis {
  position: string; // Validated position (may differ if input was invalid)
  originalPosition: string; // Raw input string
  currentPlayer: Player; // Whose turn it is at the analyzed position
  evaluation: Evaluation | null; // Overall evaluation of the position
  moveOptions: (Evaluation | null)[]; // Evaluation for playing in each column (1 to board width)
  depthReached?: number; // Actual depth reached during search (heuristic only)
  isHeuristic: boolean; // True if the analysis was generated by a heuristic engine
  bestMove?: number; // The 0-indexed column of the best move (solve() only)
  nodes?: number; // Total number of positions searched (solve() only)
  aborted?: boolean; // True if the search was aborted prematurely (exact mode only)
}

/**
 * The core WASM Bridge Interface.
 */
export interface SolverModule {
  stringToNewUTF8(str: string): number;
  _createCache: (
    w: number,
    h: number,
    bytes: number,
    is_heuristic: boolean,
  ) => number;
  _destroyCache: (ptr: number) => void;
  _createSolver: (
    w: number,
    h: number,
    cachePtr: number,
    is_heuristic: boolean,
  ) => number;
  _destroySolver: (
    w: number,
    h: number,
    ptr: number,
    is_heuristic: boolean,
  ) => void;
  _createBook: (w: number, h: number, pathPtr: number) => number;
  _createBookFromBuffer: (
    w: number,
    h: number,
    ptr: number,
    size: number,
  ) => number;
  _convertBookToDense: (w: number, h: number, ptr: number) => number;
  _convertBookToEF: (w: number, h: number, ptr: number) => number;
  _getBookFormat: (w: number, h: number, ptr: number) => number;
  _getBookScore: (w: number, h: number, ptr: number, posPtr: number) => number;
  _destroyBook: (w: number, h: number, ptr: number) => void;
  _analyzeExact: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    weak: boolean,
    threads: number,
    bookPtr: number,
    timeout: number,
  ) => number;
  _analyzeHeuristic: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    threads: number,
    max_depth: number,
    timeout: number,
  ) => number;
  _solveExact: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    weak: boolean,
    threads: number,
    bookPtr: number,
    timeout: number,
  ) => number;
  _solveHeuristic: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    depth: number,
    threads: number,
    timeout: number,
    bookPtr: number,
  ) => number;
  _stopSolver: (
    w: number,
    h: number,
    solverPtr: number,
    is_heuristic: boolean,
  ) => void;
  _getNodeCount: (
    w: number,
    h: number,
    solverPtr: number,
    is_heuristic: boolean,
  ) => number;
  UTF8ToString(pointer: number): string;
  _malloc(size: number): number;
  _free(pointer: number): void;
  wasmMemory: WebAssembly.Memory;
  onRuntimeInitialized?: () => void;
  FS: { writeFile(path: string, data: Uint8Array): void };
  getValue(ptr: number, type: string): number;
  HEAPU8: Uint8Array;
}

/**
 * Base abstract class for Connect 4 solvers.
 * All methods are async — sync WASM implementations wrap results in Promise.resolve().
 */
export abstract class BaseConnect4Solver {
  public width: number;
  public height: number;
  protected initialized = false;
  protected _bookPtr: number | string | object = 0;

  constructor(
    widthOrOpts?: number | Connect4SolverOptions,
    heightOpt?: number,
  ) {
    let width = 7;
    let height = 6;

    if (typeof widthOrOpts === "number") {
      width = widthOrOpts;
      if (heightOpt !== undefined) height = heightOpt;
    } else if (widthOrOpts && typeof widthOrOpts === "object") {
      if (widthOrOpts.width !== undefined) width = widthOrOpts.width;
      if (widthOrOpts.height !== undefined) height = widthOrOpts.height;
    }

    if (width < 4 || width > 13 || height < 4 || height > 13) {
      throw new Error(
        `Board size ${width}x${height} is outside the supported range (4x4 to 13x13).`,
      );
    }
    if (width * (height + 1) > 128) {
      throw new Error(
        `Board size ${width}x${height} exceeds the maximum supported 128-bit position mask.`,
      );
    }
    this.width = width;
    this.height = height;
  }

  protected sanitizeOpts(opts?: AnalyzeOptions & { weak?: boolean }): {
    threads: number;
    maxDepth: number;
    timeoutMs: number;
    bookPtr: number | string | object;
    weak: boolean;
  } {
    let threads = opts?.threads ?? 1;
    if (
      typeof threads !== "number" ||
      isNaN(threads) ||
      threads < 1 ||
      !isFinite(threads)
    )
      throw new Error("Invalid 'threads' parameter.");
    threads = Math.floor(threads);

    const requestedMaxDepth = opts?.maxDepth ?? this.width * this.height;
    if (
      typeof requestedMaxDepth !== "number" ||
      isNaN(requestedMaxDepth) ||
      requestedMaxDepth < 1 ||
      !isFinite(requestedMaxDepth)
    )
      throw new Error("Invalid 'maxDepth' parameter.");
    const maxDepth = Math.min(
      Math.floor(requestedMaxDepth),
      this.width * this.height,
    );

    const timeoutMs = opts?.timeoutMs ?? 0;
    if (
      typeof timeoutMs !== "number" ||
      isNaN(timeoutMs) ||
      timeoutMs < 0 ||
      !isFinite(timeoutMs)
    )
      throw new Error(
        "Invalid 'timeoutMs' parameter. Must be greater than or equal to 0.",
      );

    const bookPtr = opts?.book?.ptr ?? this._bookPtr;
    const isInvalid =
      opts?.book &&
      ((typeof bookPtr !== "number" &&
        typeof bookPtr !== "string" &&
        typeof bookPtr !== "object") ||
        (typeof bookPtr === "number" && isNaN(bookPtr)));

    if (isInvalid) throw new Error("Invalid 'book' parameter.");

    return { threads, maxDepth, timeoutMs, bookPtr, weak: opts?.weak ?? false };
  }

  abstract init(): Promise<void>;
  abstract analyze(
    positionStr: string,
    opts?: AnalyzeOptions,
  ): Promise<PositionAnalysis>;
  abstract solve(
    positionStr: string,
    opts?: AnalyzeOptions & { weak?: boolean },
  ): Promise<PositionAnalysis>;
  abstract loadBook(data: Uint8Array): Promise<void>;
  /**
   * Signals the solver to abort the current search.
   * NOTE: This is only supported on Node.js. On WASM/React Native, the JS thread is blocked during search.
   * Use timeoutMs to guarantee a maximum search time on those platforms.
   */
  abstract stop(): void;
  abstract release(): void;
  abstract getNodeCount(): Promise<number>;
}
