export enum Player {
  P1 = "P1", // Moves first
  P2 = "P2", // Moves second
}

export enum Outcome {
  Win = "Win",
  Loss = "Loss",
  Draw = "Draw",
}

export interface Connect4SolverOptions {
  width?: number;
  height?: number;
  cacheSizeMb?: number;
  heuristic?: boolean;
}

export interface AnalyzeOptions {
  threads?: number;
  maxDepth?: number;
  timeoutMs?: number;
  book?: { ptr: number };
}

export function calculateWDL(
  val: number,
  isExact: boolean,
  exactOutcome?: Outcome,
): { win: number; draw: number; loss: number } {
  if (isExact) {
    if (exactOutcome === Outcome.Win) return { win: 1.0, draw: 0.0, loss: 0.0 };
    if (exactOutcome === Outcome.Loss)
      return { win: 0.0, draw: 0.0, loss: 1.0 };
    return { win: 0.0, draw: 1.0, loss: 0.0 };
  }
  const K = 4.0;
  const pWin = 1 / (1 + Math.exp(-val / K));
  const pLoss = 1 - pWin;
  const drawWidth = 0.5;
  const pDraw = Math.exp(-(val * val) / drawWidth);
  const total = pWin + pLoss + pDraw;
  return { win: pWin / total, draw: pDraw / total, loss: pLoss / total };
}

export interface Evaluation {
  eval: {
    value: number; // Normalized float (+Infinity/-Infinity for exact wins)
    wdl: {
      win: number; // % chance of winning (0.0 to 1.0)
      draw: number; // % chance of drawing (0.0 to 1.0)
      loss: number; // % chance of losing (0.0 to 1.0)
    };
  };
  outcome?: Outcome; // Only present on exact solutions
  winner?: Player | null; // null when Draw, only present on exact solutions
  movesToEnd?: number | null; // null when Draw, only present on exact solutions
  score: number; // raw score (positive = current player winning)
}

export interface PositionAnalysis {
  position: string; // Validated position (may differ if input was invalid)
  originalPosition: string; // Raw input string
  currentPlayer: Player; // Whose turn it is at the analyzed position
  evaluation: Evaluation | null; // Overall evaluation of the position
  moveOptions: (Evaluation | null)[]; // Evaluation for playing in each column (1 to board width)
  depthReached?: number; // Actual depth reached during search
  isHeuristic: boolean; // True if the analysis was generated by a heuristic engine
}

/**
 * The core WASM Bridge Interface.
 *
 * WebAssembly does not natively support garbage collection or complex objects.
 * This interface bridges the TypeScript boundary to the C++ runtime using
 * raw integer memory pointers.
 *
 * IMPORTANT: Because memory is allocated in the WASM heap, developers MUST
 * manually call the respective _destroy* methods to prevent memory leaks.
 */
export interface SolverModule {
  stringToNewUTF8(str: string): number;
  /** Allocates a Transposition Table in the WASM heap. Returns a raw pointer. */
  _createCache: (
    w: number,
    h: number,
    bytes: number,
    is_heuristic: boolean,
  ) => number;
  /** Frees a Transposition Table from the WASM heap. */
  _destroyCache: (ptr: number) => void;

  /** Initializes a Solver bound to a specific Cache pointer. */
  _createSolver: (
    w: number,
    h: number,
    cachePtr: number,
    is_heuristic: boolean,
  ) => number;
  /** Destroys the Solver instance (but does NOT free the cache). */
  _destroySolver: (
    w: number,
    h: number,
    ptr: number,
    is_heuristic: boolean,
  ) => void;

  _createBook: (w: number, h: number, pathPtr: number) => number;
  _destroyBook: (w: number, h: number, ptr: number) => void;
  _analyzeExact: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    threads: number,
    bookPtr: number,
  ) => number;
  _analyzeHeuristic: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    threads: number,
    max_depth: number,
    timeout: number,
  ) => number;
  _getNodeCount: (
    w: number,
    h: number,
    solverPtr: number,
    is_heuristic: boolean,
  ) => number;
  UTF8ToString(pointer: number): string;
  _malloc(size: number): number;
  _free(pointer: number): void;
  onRuntimeInitialized?: () => void;
  FS: {
    writeFile(path: string, data: Uint8Array): void;
  };
  getValue(ptr: number, type: string): number;
}

/**
 * Base abstract class for Connect 4 solvers to allow clean structural
 * sharing between WASM implementations and Native implementations
 * without forcing double-bundling of the WASM glue code.
 */
export abstract class BaseConnect4Solver {
  public width: number;
  public height: number;
  protected initialized = false;

  constructor(
    widthOrOpts?: number | Connect4SolverOptions,
    heightOpt?: number,
  ) {
    let width = 7;
    let height = 6;

    if (typeof widthOrOpts === "number") {
      width = widthOrOpts;
      if (heightOpt !== undefined) {
        height = heightOpt;
      }
    } else if (widthOrOpts && typeof widthOrOpts === "object") {
      if (widthOrOpts.width !== undefined) width = widthOrOpts.width;
      if (widthOrOpts.height !== undefined) height = widthOrOpts.height;
    }

    const validSizes = [
      "6x5",
      "6x6",
      "7x6",
      "7x7",
      "8x6",
      "9x7",
      "8x8",
      "9x6",
      "11x4",
    ];
    if (!validSizes.includes(`${width}x${height}`)) {
      throw new Error(
        `Board size ${width}x${height} is not supported by the generated WASM bundle.`,
      );
    }
    this.width = width;
    this.height = height;
  }

  protected sanitizeOpts(opts?: AnalyzeOptions): {
    threads: number;
    maxDepth: number;
    timeoutMs: number;
    bookPtr: number;
  } {
    let threads = opts?.threads ?? 1;
    if (
      typeof threads !== "number" ||
      isNaN(threads) ||
      threads < 1 ||
      !isFinite(threads)
    )
      throw new Error("Invalid 'threads' parameter.");
    threads = Math.floor(threads);

    const requestedMaxDepth = opts?.maxDepth ?? this.width * this.height;
    if (
      typeof requestedMaxDepth !== "number" ||
      isNaN(requestedMaxDepth) ||
      requestedMaxDepth < 1 ||
      !isFinite(requestedMaxDepth)
    )
      throw new Error("Invalid 'maxDepth' parameter.");
    const maxDepth = Math.min(
      Math.floor(requestedMaxDepth),
      this.width * this.height,
    );

    const timeoutMs = opts?.timeoutMs ?? 25;
    if (
      typeof timeoutMs !== "number" ||
      isNaN(timeoutMs) ||
      timeoutMs <= 0 ||
      !isFinite(timeoutMs)
    )
      throw new Error("Invalid 'timeoutMs' parameter. Must be greater than 0.");

    const bookPtr = opts?.book?.ptr ?? 0;
    const isInvalid =
      opts?.book &&
      ((typeof bookPtr !== "number" && typeof bookPtr !== "object") ||
        (typeof bookPtr === "number" && isNaN(bookPtr)));

    if (isInvalid) {
      throw new Error("Invalid 'book' parameter.");
    }

    return { threads, maxDepth, timeoutMs, bookPtr };
  }

  abstract init(): Promise<void>;
  abstract analyze(
    positionStr: string,
    opts?: AnalyzeOptions,
  ): PositionAnalysis | Promise<PositionAnalysis>;
  abstract analyzeAsync(
    positionStr: string,
    opts?: AnalyzeOptions,
  ): Promise<PositionAnalysis>;
  abstract getNodeCount(): number;
  abstract unload(): void;
}
