export enum Player {
  P1 = "P1", // Moves first
  P2 = "P2", // Moves second
}

export enum Outcome {
  Win = "Win",
  Loss = "Loss",
  Draw = "Draw",
}

/**
 * Thrown when a queued task is cancelled because stop() was called before it could execute.
 * Consumers should catch this and return null / discard the result — it is not an error condition.
 */
export class SolverAbortedError extends Error {
  constructor() {
    super("Solver task was cancelled by stop()");
    this.name = "SolverAbortedError";
  }
}

export interface Connect4SolverOptions {
  width?: number;
  height?: number;
  cacheSizeMb?: number;
  heuristic?: boolean;
}

export interface AnalyzeOptions {
  threads?: number;
  maxDepth?: number;
  timeoutMs?: number;
  book?: { ptr: number };
  heuristic?: boolean;
  weak?: boolean;
}

export interface Evaluation {
  eval: {
    value: number; // Normalized float (+Infinity/-Infinity for exact wins, score/100 for heuristic)
  };
  outcome?: Outcome; // Only present on exact solutions
  winner?: Player | null; // null when Draw, only present on exact solutions
  movesToEnd?: number | null; // null when Draw, only present on exact solutions
  score: number; // raw score (positive = current player winning)
}

export interface PositionAnalysis {
  position: string; // Validated position (may differ if input was invalid)
  originalPosition: string; // Raw input string
  currentPlayer: Player; // Whose turn it is at the analyzed position
  evaluation: Evaluation | null; // Overall evaluation of the position
  moveOptions: (Evaluation | null)[]; // Evaluation for playing in each column (1 to board width)
  depthReached?: number; // Actual depth reached during search (heuristic only)
  isHeuristic: boolean; // True if the analysis was generated by a heuristic engine
  bestMove?: number; // The 0-indexed column of the best move (solve() only)
  nodes?: number; // Total number of positions searched (solve() only)
  aborted?: boolean; // True if the search was aborted prematurely (exact mode only)
}

/**
 * The core WASM Bridge Interface.
 */
export interface SolverModule {
  stringToNewUTF8(str: string): number;
  _createCache: (
    w: number,
    h: number,
    bytes: number,
    is_heuristic: boolean,
  ) => number;
  _destroyCache: (ptr: number) => void;
  _createSolver: (
    w: number,
    h: number,
    cachePtr: number,
    is_heuristic: boolean,
  ) => number;
  _destroySolver: (
    w: number,
    h: number,
    ptr: number,
    is_heuristic: boolean,
  ) => void;
  _createBook: (w: number, h: number, pathPtr: number) => number;
  _createBookFromBuffer: (
    w: number,
    h: number,
    ptr: number,
    size: number,
  ) => number;
  _convertBookToDense: (w: number, h: number, ptr: number) => number;
  _convertBookToEF: (w: number, h: number, ptr: number) => number;
  _getBookFormat: (w: number, h: number, ptr: number) => number;
  _getBookScore: (w: number, h: number, ptr: number, posPtr: number) => number;
  _destroyBook: (w: number, h: number, ptr: number) => void;
  _analyzeExact: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    weak: boolean,
    threads: number,
    bookPtr: number,
    timeout: number,
  ) => number;
  _analyzeHeuristic: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    threads: number,
    max_depth: number,
    timeout: number,
  ) => number;
  _solveExact: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    weak: boolean,
    threads: number,
    bookPtr: number,
    timeout: number,
  ) => number;
  _solveHeuristic: (
    w: number,
    h: number,
    solverPtr: number,
    posPtr: number,
    depth: number,
    threads: number,
    timeout: number,
    bookPtr: number,
  ) => number;
  _stopSolver: (
    w: number,
    h: number,
    solverPtr: number,
    is_heuristic: boolean,
  ) => void;
  _getNodeCount: (
    w: number,
    h: number,
    solverPtr: number,
    is_heuristic: boolean,
  ) => number;
  UTF8ToString(pointer: number): string;
  _malloc(size: number): number;
  _free(pointer: number): void;
  wasmMemory: WebAssembly.Memory;
  onRuntimeInitialized?: () => void;
  FS: { writeFile(path: string, data: Uint8Array): void };
  getValue(ptr: number, type: string): number;
  HEAPU8: Uint8Array;
}

/**
 * Base abstract class for Connect 4 solvers.
 * All methods are async — sync WASM implementations wrap results in Promise.resolve().
 */
export abstract class BaseConnect4Solver {
  public width: number;
  public height: number;
  /** The cache size actually allocated after init(). May be less than requested if memory is tight. */
  public allocatedCacheSizeMb = 0;
  protected initialized = false;
  protected _bookPtr: number | string | object = 0;

  constructor(
    widthOrOpts?: number | Connect4SolverOptions,
    heightOpt?: number,
  ) {
    let width = 7;
    let height = 6;

    if (typeof widthOrOpts === "number") {
      width = widthOrOpts;
      if (heightOpt !== undefined) height = heightOpt;
    } else if (widthOrOpts && typeof widthOrOpts === "object") {
      if (widthOrOpts.width !== undefined) width = widthOrOpts.width;
      if (widthOrOpts.height !== undefined) height = widthOrOpts.height;
    }

    if (width < 4 || width > 16 || height < 4 || height > 16) {
      throw new Error(
        `Board size ${width}x${height} is outside the supported range (4x4 to 16x16).`,
      );
    }
    if (width * (height + 1) > 127) {
      throw new Error(
        `Board size ${width}x${height} exceeds the maximum supported 127-bit position mask.`,
      );
    }
    this.width = width;
    this.height = height;
  }

  /**
   * True if a search or analysis is currently in progress.
   */
  protected _isBusy = false;

  /**
   * Public accessor for the busy state.
   */
  public get isBusy(): boolean {
    return this._isBusy;
  }

  // ─── Internal search queue ───────────────────────────────────────────────

  protected _queue: {
    task: () => Promise<unknown>;
    resolve: (val: unknown) => void;
    reject: (err: unknown) => void;
  }[] = [];

  /** Resolves when the currently active runTask() call finishes (or null if idle). */
  private _taskSettledPromise: Promise<void> | null = null;

  /**
   * Wraps a search task with busy-tracking. Queues if busy rather than throwing.
   * Only search operations (analyze, solve) should go through runTask.
   * Book loading must NOT use runTask — call stop() before loadBook().
   */
  protected async runTask<T>(task: () => Promise<T> | T): Promise<T> {
    if (this._isBusy) {
      return new Promise<T>((resolve, reject) => {
        this._queue.push({
          task: task as () => Promise<unknown>,
          resolve: resolve as (v: unknown) => void,
          reject,
        });
      });
    }
    return this._executeTask(task);
  }

  private async _executeTask<T>(task: () => Promise<T> | T): Promise<T> {
    this._isBusy = true;
    let settle!: () => void;
    this._taskSettledPromise = new Promise<void>((r) => {
      settle = r;
    });
    try {
      const res = task();
      return res instanceof Promise ? await res : res;
    } finally {
      this._isBusy = false;
      settle();
      this._taskSettledPromise = null;
      this._processNextQueued();
    }
  }

  private _processNextQueued(): void {
    const next = this._queue.shift();
    if (!next) return;
    this._executeTask(next.task).then(next.resolve, next.reject);
  }

  protected sanitizeOpts(opts?: AnalyzeOptions): {
    threads: number;
    maxDepth: number;
    timeoutMs: number;
    bookPtr: number | string | object;
    weak: boolean;
  } {
    let threads = opts?.threads ?? 1;
    if (
      typeof threads !== "number" ||
      isNaN(threads) ||
      threads < 1 ||
      !isFinite(threads)
    )
      throw new Error("Invalid 'threads' parameter.");
    threads = Math.floor(threads);

    const requestedMaxDepth = opts?.maxDepth ?? this.width * this.height;
    if (
      typeof requestedMaxDepth !== "number" ||
      isNaN(requestedMaxDepth) ||
      requestedMaxDepth < 1 ||
      !isFinite(requestedMaxDepth)
    )
      throw new Error("Invalid 'maxDepth' parameter.");
    const maxDepth = Math.min(
      Math.floor(requestedMaxDepth),
      this.width * this.height,
    );

    const timeoutMs = opts?.timeoutMs ?? 0;
    if (
      typeof timeoutMs !== "number" ||
      isNaN(timeoutMs) ||
      timeoutMs < 0 ||
      !isFinite(timeoutMs)
    )
      throw new Error(
        "Invalid 'timeoutMs' parameter. Must be greater than or equal to 0.",
      );

    const bookPtr = opts?.book?.ptr ?? this._bookPtr;
    const isInvalid =
      opts?.book &&
      ((typeof bookPtr !== "number" &&
        typeof bookPtr !== "string" &&
        typeof bookPtr !== "object") ||
        (typeof bookPtr === "number" && isNaN(bookPtr)));

    if (isInvalid) throw new Error("Invalid 'book' parameter.");

    return { threads, maxDepth, timeoutMs, bookPtr, weak: opts?.weak ?? false };
  }

  abstract init(): Promise<void>;
  abstract analyze(
    positionStr: string,
    opts?: AnalyzeOptions,
  ): Promise<PositionAnalysis>;
  abstract solve(
    positionStr: string,
    opts?: AnalyzeOptions,
  ): Promise<PositionAnalysis>;
  abstract loadBook(data: Uint8Array): Promise<void>;

  /**
   * Sends the platform-specific abort signal to the engine.
   * Override in subclasses (do not call stop() — that is handled by the base class).
   */
  protected _sendAbortSignal(): void {
    /* no-op default */
  }

  /**
   * Signals the solver to stop the current search and all queued search tasks.
   *
   * - Sends the abort signal to the engine immediately (fire-and-forget on the C++ side).
   * - Rejects all queued search tasks with SolverAbortedError.
   * - Returns a Promise that resolves when the currently active task settles
   *   (either completes normally or aborts). After resolution, the solver is idle
   *   and safe to call analyze() on.
   *
   * NOTE: loadBook() must not be called while the solver is busy.
   * Call stop() and await the result before loading a book during active analysis.
   */
  async stop(): Promise<void> {
    this._sendAbortSignal();
    const flushed = this._queue.splice(0);
    const err = new SolverAbortedError();
    for (const item of flushed) item.reject(err);
    return this._taskSettledPromise ?? Promise.resolve();
  }

  abstract release(): void;
  abstract getNodeCount(): Promise<number>;
}
