// AUTO-GENERATED by tools/gen_embedded_books.py
// DO NOT EDIT MANUALLY. Re-run the script to regenerate.
//
// Board sizes for which an opening book is compiled directly into the binary.
// Must stay in sync with native/embedded_books.hpp.

export const EMBEDDED_BOOK_SIZES: ReadonlySet<string> = new Set([
  "6x6",
  "6x7",
  "7x6",
]);
